### ISSUE TITLE
`relation "public.notification_send_history_summary" does not exist"`

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#1190]
occurs on aws-demo

**Comment by adityathebe** [comment]
@moshloop I'm not seeing that error 

https://flanksource.grafana.net/explore?schemaVersion=1&panes=%7B%22l2x%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22aws-demo%5C%22%7D%20%7C%3D%20%60does%20not%20exist%60%20%21%3D%20%60aditya%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1

**Comment by adityathebe** [comment]
https://github.com/flanksource/duty/blob/main/functions/drop.sql

if this file runs during migration and the view creation file `021_notification.sql` doesn't - then the view gets dropped.
