### ISSUE TITLE
Attribute code copied from ariga/atlas

### ISSUE THREAD

**Issue by rotemtam** [flanksource/duty#259]
Hey @moshloop,

I am happy to see this project use Atlas for schema management.

Directing your attention to the code in [this file](https://github.com/flanksource/duty/blob/02d30b6661d66002de87de2314c3f46fa3e96da5/schema/apply.go) which contains code that was mostly copied our repo. As this code is licensed under Apache 2, I kindly remind you that license and copyright information must be preserved in derivative work.

Thanks in advance

**Comment by moshloop** [comment]
Hi @rotemtam 

Thanks for picking this up - We have updated this in https://github.com/flanksource/duty/pull/293 - let me know if applies attribution correctly?

We also created an issue https://github.com/ariga/atlas/issues/2136 for why we needed todo this.
