### ISSUE TITLE
Error fetching analysis_by_component 

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/duty#286]
```
{
  "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",
  "errorType": "Function.ResponseSizeTooLarge"
}
```

**Comment by moshloop** [comment]
@mainawycliffe - How do we reproduce this? Is this not perhaps a paging issue of trying to return all rows?

**Comment by mainawycliffe** [comment]
I can't seem to be able to reproduce this again, happened a couple of times, will keep an eye on it, may be add a limit on rows for the components.

**Comment by adityathebe** [comment]
@moshloop This seems more like an error rather than a response with large number of rows. I don't think we'd have that many results for `analysis_by_component`.

Azure: 10
AWS: 0
