### ISSUE TITLE
Trace upstream pushes/pulles

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#292]

**Comment by moshloop** [comment]
I think also we should extract https://github.com/flanksource/canary-checker/blob/master/pkg/http/client.go, maybe into commons (minus the CheckJSONcontent)  and then add an option for tracing (with and without request  / response body) to be use for the upstream http client

**Comment by adityathebe** [comment]
@moshloop It seems like we already do have an existing http client on commons https://github.com/flanksource/commons/blob/master/http/client.go.

Will remove that & use canary-checker's as it seems to be the recent one.
