### ISSUE TITLE
Topology query metadata

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#97]
In the topology results provide a list of:
- health status
- teams
- tags
- types

so that the UI only shows valid options

**Comment by adityathebe** [comment]
As I understand, UI makes multiple calls to populate the dropdowns in the topology page

```
/api/db/teams
/api/db/component_names
/api/db/component_labels

# health is probably hardcoded ?
```

Do I need to update the topology endpoint in canary-checker to return a response something like this _(so we get everything we want in a single call)_?

```
type TopologyRes struct {
	Components     models.Components `json:"components,omitempty"`
	HealthStatuses []string          `json:"healthStatuses,omitempty"`
	Teams          []string          `json:"teams,omitempty"`
	Tags           []string          `json:"tags,omitempty"`
	Types          []string          `json:"types,omitempty"`
}
```

**Comment by yashmehrotra** [comment]
Addressed by https://github.com/flanksource/duty/pull/129
